### ISSUE TITLE
How do I fix this

### ISSUE THREAD

**Issue by claymorwan** [husseinhareb/dotfiles-i3-#1]
Polybar seems to be offset or cut for some reason
![image](https://github.com/husseinhareb/dotfiles-i3-/assets/86072589/d4a0d30b-c7e3-4b23-8593-e8379ff754cc)

**Comment by husseinhareb** [comment]
Set override-redirect to true, install Cava, download the necessary scripts, and put them in the correct path or fix the path in the Polybar config.

**Comment by claymorwan** [comment]
override-redirect in polybar's config.ini file ?
And do I have t put the scripts in the .config folder before doing chmod +x ?

**Comment by husseinhareb** [comment]
Yes, add `override-redirect = true` to the bar settings. Concerning the file paths, you have two options:

1. Put the files in the same paths according to the Polybar configurations.
2. Change the paths in the Polybar config according to the files' locations.

Either way, you have to download the files and give them the correct permissions using `chmod +x file_name`. Additionally, you have to install Cava. If you are on Arch Linux, install `cava-git` from the AUR.

I also advise you to try newer Polybar configs that I created, which look better in my opinion, like [here](https://github.com/husseinhareb/qtile-config) and [here](https://github.com/husseinhareb/my-dotfiles).

If you need further help, you can contact me on my Discord.

**Comment by claymorwan** [comment]
I got it working thanks, there's just the backlight model which seems to not be showing up, but except of that it's working thanksu :3

**Comment by husseinhareb** [comment]
Glad to know it's working. Concerning the backlight, can you send me the output of this command:

```sh
ls -1 /sys/class/backlight/
```

**Comment by claymorwan** [comment]
It outputs `intel_backlight`

**Comment by husseinhareb** [comment]
In my case, the graphics card is an NVIDIA, but in your case, it's an Intel GPU. This is why you have to change the

```ini
[module/backlight]
type = internal/backlight
card = nvidia_0  
use-actual-brightness = true
```

to

```ini
[module/backlight]
type = internal/backlight
card = intel_backlight  
use-actual-brightness = true
```


Once you set the card to `intel_backlight`, you should be good to go. If this is the last issue you are dealing with in the configuration, please inform me so I can mark the issue as closed.

**Comment by claymorwan** [comment]
O it seems to be working now, thanksu :3, btw I checked u're other polybar config, I'll keep them in mind once I try Qtile

**Comment by husseinhareb** [comment]
No need to try Qtile if you don't want to. All of my bars are Polybar bars, so you can use them with whatever window manager you are using. Anyhow, I'll close the issue now since everything is working for you.
