### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by Twilight876** [husseinhareb/dotfiles-i3-#2]
Why my desktop look like this
![20240813_161833](https://github.com/user-attachments/assets/f6398ea1-5504-4265-8781-3fdd7477c863)
And can you please write shortcuts of rofi and terminal,etc

**Comment by husseinhareb** [comment]
Grab the JetBrainsMono Nerd Font from here: [link](https://www.nerdfonts.com/font-downloads).
It's the JetBrainsMono Nerd Font, which is necessary for the icons to load properly.

You can find the bindings for Rofi and other configurations inside the .config/i3/config file.
Here, you can view and modify all the bindings. For example, the terminal binding is:


```
#Start a terminal
bindsym $mod+Return exec kitty # Super + Enter
```

For Rofi:

`bindsym $mod+q exec --no-startup-id rofi -show drun -show-icons # Super + Q`

And so on...

**Comment by Twilight876** [comment]
Ok thank you

**Comment by husseinhareb** [comment]
You are welcome. I will close the issue now. If you have further questions, please open a new one.
